# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0d54e12231535c746b4bd452e7cf17ce"
name = "Test Dev 13 app"
handle = "test-dev-13-app"
application_url = "https://spy-lebanon-sheets-hey.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-13.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,write_discounts_allocator_functions,write_products"

[auth]
redirect_urls = [
  "https://spy-lebanon-sheets-hey.trycloudflare.com/auth/callback",
  "https://spy-lebanon-sheets-hey.trycloudflare.com/auth/shopify/callback",
  "https://spy-lebanon-sheets-hey.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false
